### ISSUE TITLE
Open a ycominator.com link with app

### ISSUE THREAD

**Issue by zhudhjen** [dinosaurwithakatana/hacker-news-android#28]
I recieve pushes of hacker news best via pushbullet. It sends links and I have to reas them in browser. I wish to open these links with app, just like Pinterest or twitter.

**Comment by burntcookie90** [comment]
Yep, good idea, I should be able to get that in this weekend

**Comment by burntcookie90** [comment]
Added: https://github.com/dinosaurwithakatana/hacker-news-android/commit/fdbe90e575ebda7fcf0570b5439639e6db38a655

**Comment by azizLIGHT** [comment]
Thanks for implementing this. I have the same use case as zhudhjen and appreciate the update

**Comment by burntcookie90** [comment]
No problem, it's something I had thought about but then it passed my mind. It was simple enough :)
