### ISSUE TITLE
High data usage with internal browser disabled

### ISSUE THREAD

**Issue by pozibrothers** [dinosaurwithakatana/hacker-news-android#32]
The application is consuming much more data than it should with internal browser disabled (option `Show link first` is disabled and `Open links in system browser` is enabled). In just five days (since the beggining of the month) it has used 38.93MB of data.

Could it be that the application is loading webpages even with the option disabled? 

Currently I'm running app version 2.7 in a Nexus 5 running Lollipop 5.0.1.

**Comment by burntcookie90** [comment]
No, that's not possible. As you can see [here](https://github.com/dinosaurwithakatana/hacker-news-android/blob/master/app/src/main/java/io/dwak/holohackernews/app/ui/storydetail/StoryDetailFragment.java#L234) the browser only loads the url the first time if you press the button for the internal browser, or if show link first is enabled.

For me, all of last month the app used 43mb with internal browser enabled. Though I can look into data usage, there are very few data calls (disregarding the internal browser). I make a call for the first 30 stories, and when you begin scrolling to the bottom I make the call for the next 30. The call for a story's details (comments, link, etc) is only made when a story is selected.

Let me take a look though.

**Comment by pozibrothers** [comment]
Hi.

Definitely, the application is loading links in background with the settings I described in my first post.

I can reproduce this behaviour doing the following:

1.- Uninstall application.
2.- Reinstall from Play Store (I'm subscribed to beta from G+).
3.- Enter app and check `Open links in system browser`.
4.- Load a random post and wait some time.
5.- Press `Show link` option.

Result:

The webpage is rendered instantly without loading time.

Expected result:

The webpage should not be rendered instantly as it would have to wait for download of text and assets.

I hope this helps.

**Comment by burntcookie90** [comment]
@pozibrothers, it seems you were right! I can hopefully get some time to work on this over the weekend (been travelling a lot recently).

**Comment by pozibrothers** [comment]
I just realized that the problem might be a different thing... I think the option `Open links in system browser` is reversed. If I check the option, links load in internal browser. If I uncheck it and press `Show link` it opens in system browser.

So, you were right, it only loads if the option is enabled. But the functionality is reversed.

**Comment by burntcookie90** [comment]
Hm, something must have gone wacko, I may have to look at this tonight then. I'll update the ticket accordingly, thanks for the report!

**Comment by burntcookie90** [comment]
If you clear the app data, does this issue come up?
