### ISSUE TITLE
Rotation from portrait to landscape does not resize scrollview

### ISSUE THREAD

**Issue by nguyenmp** [dinosaurwithakatana/hacker-news-android#34]
Open the app to view the list of posts. 

Rotate device to be in landscape mode. 

Click a link to view comments. 

Rotate to portrait mode. Observe that the scroll view does not properly resize.

http://imgur.com/UlD2bVm

**Comment by burntcookie90** [comment]
Interesting, thanks for the report, I'll take a look at it soon
