### ISSUE TITLE
Return to scroll position in previous thread

### ISSUE THREAD

**Issue by azizLIGHT** [dinosaurwithakatana/hacker-news-android#35]
This is a very minor usability improvement that mirrors Reddit News behavior. 
Right now, if you accidentally back out of a thread while reading and try to return to the same post from the thread list, the thread will reload from the start and you will have to go find where you left off to resume reading. It would be useful if we can go back to the thread and resume reading from the scroll position we were at. The scroll position should probably be forgotten if we go to a different post rather than the same one, and it should remember the new post's scroll position in the same manner instead.

**Comment by burntcookie90** [comment]
So i think this is an implementation detail with how Reddit News does their swiping. It seems like dbrady has utilized a viewpager (at least from the animation and how the details view doesn't lose position until a new story is navigated to). Unfortunately, handling that might be a little cumbersome, and actually quite different from how almost every other application handles this situations :/

**Comment by azizLIGHT** [comment]
It sounds like it's a very minor improvement for too much effort.
