### ISSUE TITLE
Urls enclosed in parenthesis in "self" text posts are not clickable

### ISSUE THREAD

**Issue by azizLIGHT** [dinosaurwithakatana/hacker-news-android#38]
For example: https://news.ycombinator.com/item?id=9085750

Urls surrounded by parenthesis inside the post description cannot be clicked on. I checked if comments had this problem, and they don't. Only the "self" text (not sure what to call it) 

(http://www.goo

**Comment by azizLIGHT** [comment]
Well I noticed it's the same on my browsers, so maybe this isn't a bug

**Comment by burntcookie90** [comment]
Yeah, this isn't being returned as a link in the post content, so I don't think I can do much on that :/
