### ISSUE TITLE
Request: Copy comment text

### ISSUE THREAD

**Issue by azizLIGHT** [dinosaurwithakatana/hacker-news-android#41]
Let's say someone posts a comment with long regex or a bunch of email addresses or a famous quote. Assuming you want to look it up or act on it in some way, you would have to open the comments page in your browser and scroll to where the comment was in order to copy it. 
Could we copy the comment text directly from the app instead? Maybe by long pressing the comment in question, and getting an option to do so?

**Comment by burntcookie90** [comment]
Yeah I can add it to the comment's overflow, you can currently share the content to your clipboard with Google Drive's "copy to clipboard" intent.

**Comment by azizLIGHT** [comment]
I see. I missed the overflow menu on the comment because it's very hard to see on night mode

**Comment by azizLIGHT** [comment]
The share comment content >> Copy to clipboard idea works for me.
