### ISSUE TITLE
Importing into Android Studio fails

### ISSUE THREAD

**Issue by OneKorg** [dinosaurwithakatana/hacker-news-android#43]
Importing my fork of the project through the Android studio interface fails.
the error shown is : 
`Neither path nor baseDir may be null or empty string path='null' basedir='/path/to/project'`
tried to google the problem and it most likely is an issue with build.grade in the app directory

**Comment by OneKorg** [comment]
this is the line causing the problem 
https://github.com/dinosaurwithakatana/hacker-news-android/blob/master/app/build.gradle#L19
after commenting the whole block I was able to build the app

**Comment by burntcookie90** [comment]
Correct, you need to create a `keystore.properties` file as shown here: https://github.com/dinosaurwithakatana/hacker-news-android/blob/master/keystore.properties.example

and fill it with your own keystore. I dont think this is necessary for debug builds though
