### ISSUE TITLE
Collapsible comments

### ISSUE THREAD

**Issue by burntcookie90** [dinosaurwithakatana/hacker-news-android#5]

**Comment by azizLIGHT** [comment]
A click-to-collapse comment implementation works best, in my opinion. You could collapse whole comment threads by tapping the parent comment, or specific comments under the parent and it's replies with a single tap without affecting the parent comment or other subcomments. It allows you to hide comments that you are done reading and to allow faster comment navigation. If need be, you could click-to-expand collapsed comments, at any level.

An example of this is implemented nicely in the "Reddit News" app on Android. Clicking a comment does a collapse, and other detailed options, like upvoting/downvoting, are accessed by swiping left.

I've seen other apps implement a popup menu that appears when tapping a comment and gives options like upvote/collapse comment/collapse thread/share/copy text/go to user profile. In my opinion, this makes the menu too busy if all you're trying to do is navigate comments, and options like those that go beyond comment collapsing should go elsewhere that don't interfere with navigation.

**Comment by burntcookie90** [comment]
Yeah, I would love to implement the Reddit News style collapsing, I prefer it over Reddit Sync's version. However, I'm still a little befuddled on how to implement it programmatically. I'm thinking about switching the comments view over to RecyclerView soon and will take a stab at it then.

**Comment by azizLIGHT** [comment]
Here's three HN apps that implement it
- https://github.com/manmal/hn-android/ | https://play.google.com/store/apps/details?id=com.manuelmaly.hn
- https://github.com/bishopmatthew/HackerNews | https://play.google.com/store/apps/details?id=com.airlocksoftware.hackernews
- https://github.com/rickylaishram/Hacker-News-Android | https://play.google.com/store/apps/details?id=com.rickylaishram.hackernews&hl=en

Hope it helps!

**Comment by burntcookie90** [comment]
oh cool, thanks!

**Comment by burntcookie90** [comment]
@azizLIGHT Please check the beta once it is distributed, I have pushed initial functionality towards this feature.

**Comment by azizLIGHT** [comment]
I look forward to testing it out!

**Comment by azizLIGHT** [comment]
This is looking pretty good once I figured out how to get it to work. It wasn't obvious because I was expecting it to collapse by pressing anywhere on the comment. Instead you have to click specifically near the top of the comment to get it to work. Is there any particular reason why you chose a small area where the collapsing to activate from?

**Comment by azizLIGHT** [comment]
Also, is this causing issues with comment counts? I know that best articles don't have 4 comments, because I can go there and see at least 10 top level comments. 

Lastly, after collapsing a top level comment, the next top level comment is not separated enough visually from the previous. Maybe add some kind of divider?

**Comment by burntcookie90** [comment]
I do need to figure out a better zone for the action, (it's in beta :D).

Comment counts was caused by an api issue, I'll be looking into it this weekend

**Comment by burntcookie90** [comment]
The update pushed to production just now supports full container clicks for collapsing of comments.

I need to open a bug on cheeauns API about the comment count. Closing this ticket for now
