### ISSUE TITLE
Contextual ActionBar not overlayed (when selecting in WebView)

### ISSUE THREAD

**Issue by DreaminginCodeZH** [dinosaurwithakatana/hacker-news-android#56]
Please see http://stackoverflow.com/questions/26443403/toolbar-and-contextual-actionbar-with-appcompat-v7 for the problem and solution.

**Comment by burntcookie90** [comment]
Awesome, thanks for the report, will take a look

**Comment by heypaulmcgrath** [comment]
+1 same issue

**Comment by burntcookie90** [comment]
@DreaminginCodeZH if you are in the beta community, can you check if this is fixed?

**Comment by DreaminginCodeZH** [comment]
Sorry, but I haven't been in that yet...

Vishnu Rajeevan <notifications@github.com>于2015年7月21日星期二 23:41写道：

> @DreaminginCodeZH <https://github.com/DreaminginCodeZH> if you are in the
> beta community, can you check if this is fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dinosaurwithakatana/hacker-news-android/issues/56#issuecomment-123377023>
> .
>
-- 
张海
浙江大学 计算机科学与技术
Blog: http://blog.zhanghai.me/
Github: https://github.com/DreaminginCodeZH
