### ISSUE TITLE
Links not visible on Moto X Play running Android M

### ISSUE THREAD

**Issue by harshil93** [dinosaurwithakatana/hacker-news-android#79]
![screenshot_20160123-112751](https://cloud.githubusercontent.com/assets/1177554/12531904/540f1142-c22c-11e5-8626-89ed5f9f5aef.png)

![capture](https://cloud.githubusercontent.com/assets/1177554/12531906/780d77b4-c22c-11e5-8b4f-29776b59296b.PNG)

**Comment by burntcookie90** [comment]
I recently saw this on a friends 6p, I'll try and get a fix in this weekend

**Comment by harshil93** [comment]
Thanks @burntcookie90. I was working on a fix but couldn't test it because of slow internet at home(it needs 6.0 sdk). 
Are there any important features enhancements which I can contribute to. I am usually free on weekends

**Comment by burntcookie90** [comment]
The master / development branches are currently frozen (minus major but fixes). The application is currently undergoing a full rewrite on the branch feature/kotlin. Once that branch becomes stable I'll let you know. Thanks!
